import json
LISTA_CHAVES = [
    [
        "Seguro residencial ",
        "Seguro prestamista",
        "Seguro habitacional ",
        "Correção monetária ",
        "Juros abusivos ",
        "Juros",
        "Honorários de sucumbencia",
        "Taxa selic",
        "Seguro de vida",
        "Doença preexistente",
        "Seguro automóvel",
        "Agravamento de risco",
        "Cobertura securitária",
        "Sinistro",
        "Indenização securitária",
        "Cláusula de exclusão",
        "Prêmio de seguro",
        "Franquia",
        "Reajuste de prêmio",
        "Seguro residencial",
        "Seguro de responsabilidade civil",
        "Boa-fé contratual",
        "Perda total",
        "Venda casada",
        "Devolução de prêmio",
        "Mora do devedor",
        "Equiparação salarial",
        "Horas extras",
        "Justa causa",
        "Assédio moral"
    ],
    [
        "Acidente de trabalho",
        "Vínculo empregatício",
        "Rescisão contratual",
        "Fundo de Garantia",
        "Adicional de periculosidade",
        "Adicional de insalubridade",
        "Estabilidade provisória",
        "Férias",
        "Décimo terceiro salário",
        "Negociação coletiva",
        "Direito sindical",
        "Bancário ",
        "Hora adicional",
        "Gerente de agência ",
        "Gernte Bancário",
        "Honorários periciais ",
        "Incompetência absoluta ",
        "Incompetência relativa",
        "Juros de mora",
        "Locacao",
        "Despejo",
        "Inquilino ",
        "Mora do devedor ",
        "Valuation",
        "Assédio moral",
        "Balanço específico ",
        "Prática abusiva",
        "Vício do produto",
        "Defeito do produto ",
        "Direito de arrependimento"
    ],
    [
        "Publicidade enganosa",
        "Proteção contratual",
        "Oferta e demanda",
        "Serviço defeituoso",
        "Cobrança indevida",
        "Produto defeituoso",
        "Cláusulas abusivas",
        "Direitos básicos do consumidor",
        "Responsabilidade do fornecedor",
        "Prazo de garantia",
        "Ação de reparação de danos",
        "Serviço não fornecido",
        "Boa fé ",
        "Má fé ",
        "Dano moral",
        "Dano material",
        "Contratos",
        "Posse",
        "Usucapião",
        "Direitos reais",
        "Obrigação de fazer",
        "Responsabilidade civil",
        "Atos ilícitos",
        "Capacidade civil",
        "Interdito proibitório",
        "Inventário e partilha",
        "Direito das sucessões",
        "Direito Previdenciário",
        "Aposentadoria",
        "Benefício por incapacidade"
    ],
    [
        "Pensão por morte",
        "Contribuição previdenciária",
        "Auxílio-doença",
        "Auxílio-acidente",
        "Salário-maternidade",
        "Desaposentação",
        "Carência",
        "Tempo de contribuição",
        "Regime geral de previdência",
        "Benefício assistencial",
        "LOAS",
        "Fator previdenciário",
        "Revisão de benefício",
        "Direito Administrativo",
        "Licitação",
        "Concurso público",
        "Improbidade administrativa",
        "Serviço público",
        "Ato administrativo",
        "Processo administrativo",
        "Servidor público",
        "Regime jurídico único",
        "Controle da administração",
        "Responsabilidade fiscal",
        "Concessão de serviço público",
        "Direito urbanístico",
        "Patrimônio público",
        "Intervenção do Estado na propriedade",
        "Autarquia",
        "Direito Constitucional"
    ],
    [
        "Direitos fundamentais",
        "Controle de constitucionalidade",
        "Mandado de segurança",
        "Ação direta de inconstitucionalidade",
        "Direito à vida",
        "Liberdade de expressão",
        "Direitos sociais",
        "Federalismo",
        "Separação de poderes",
        "Direitos políticos",
        "Estado Democrático de Direito",
        "Poder constituinte",
        "Habeas data",
        "Ação civil pública",
        "Direitos humanos",
        "Direito de Família",
        "Divórcio",
        "Guarda de menores",
        "Pensão alimentícia",
        "União estável",
        "Tutela",
        "Adoção",
        "Alimentos",
        "Direito de visitas",
        "Regime de bens",
        "Paternidade",
        "Investigação de paternidade",
        "Interdição",
        "Testamento",
        "Herança"
    ],
    [
        "Partilha de bens",
        "Direito penal",
        "Habeas corpus",
        "Prisão preventiva",
        "Crime ambiental",
        "Lavagem de dinheiro",
        "Furto",
        "Roubo",
        "Furto simples",
        "Furto qualificado ",
        "Estelionato",
        "Homicídio",
        "Tráfico de drogas",
        "Lesão corporal",
        "Crimes cibernéticos",
        "Corrupção",
        "Peculato",
        "Sonegação fiscal",
        "Imputabilidade penal",
        "União estável",
        "Regime de separação parcial",
        "Regime de separação total",
        "Adoção ",
        "Curatela",
        "Correspondente bancario",
        "Usucapião rural",
        "Reforma agrária",
        "Desapropriação para fins de reforma agrária",
        "Conflito de terras",
        "Terra devoluta"
    ],
    [
        "Imóvel rural",
        "Cadastro rural",
        "Contrato agrário",
        "Arrendamento rural",
        "Parceria agrícola",
        "Direito de preferência",
        "Crédito rural",
        "Produtor rural",
        "Seguro agrícola",
        "Sustentabilidade no campo",
        "Cyber Direito ",
        "Privacidade na internet",
        "Proteção de dados pessoais",
        "Comércio eletrônico",
        "Contratos digitais",
        "Direito autoral digital",
        "Crimes cibernéticos",
        "Assinatura digital",
        "Certificação digital",
        "Governança digital",
        "Redes sociais e direito",
        "Inteligência artificial e direito",
        "E-commerce e responsabilidade",
        "Fake news e responsabilidade legal",
        "Cibersegurança",
        "Blockchain e direito",
        "Provas Digitais",
        "Autenticidade de documentos digitais",
        "Cadeia de custódia digital",
        "Forense computacional"
    ],
    [
        "Análise de dados digitais",
        "Rastreamento de IP",
        "Recuperação de dados",
        "Criptografia e provas digitais",
        "Assinaturas eletrônicas",
        "Interceptação de comunicações digitais",
        "Malware e análise forense",
        "Cloud computing e investigações",
        "Privacidade e vigilância digital",
        "Big data como prova legal",
        "Redes sociais como evidência",
        "Metadados e relevância probatória",
        "Geolocalização ",
        "Inversão do ônus da prova",
        "Prova testemunhal",
        "Prova documental",
        "Prova pericial",
        "Prova digital",
        "Presunção de veracidade",
        "Cadeia de custódia",
        "Ônus da prova",
        "Prova ilícita",
        "Interrogatório",
        "Depoimento pessoal",
        "Confissão",
        "Acareação",
        "Prova emprestada",
        "Prova técnica",
        "Laudo pericial",
        "Valor probatório"
    ],
    [
        "Provas ilícitas por derivação",
        "Preservação de provas",
        "Prova indiciária",
        "Incidente de falsidade",
        "Prova circunstancial",
        "Vistoria",
        "Reconhecimento de pessoas e coisas",
        "Preclusão probatória",
        "Direito Penal Econômico",
        "Crime contra a ordem econômica",
        "Lavagem de dinheiro",
        "Sonegação fiscal",
        "Concorrência desleal",
        "Fraude fiscal",
        "Insider trading",
        "Crime contra o sistema financeiro",
        "Mercado de capitais",
        "Pirâmide financeira",
        "Gestão fraudulenta",
        "Evasão de divisas",
        "Fraude em licitações",
        "Crime contra as relações de consumo",
        "Corrupção empresarial",
        "Falência fraudulenta",
        "Direito Militar",
        "Crime militar",
        "Justiça militar",
        "Código Penal Militar",
        "Hierarquia e disciplina",
        "Deserção"
    ],
    [
        "Insubordinação",
        "Motim",
        "Tribunal Militar",
        "Ato de serviço",
        "Penalidades militares",
        "Processo penal militar",
        "Regulamento disciplinar",
        "Estatuto dos Militares",
        "Reforma militar",
        "Acidente em serviço",
        "Direito Eleitoral",
        "Direitos políticos",
        "Inelegibilidade",
        "Registro de candidatura",
        "Propaganda eleitoral",
        "Financiamento de campanha",
        "Urna eletrônica",
        "Voto obrigatório",
        "Ação de impugnação de mandato eletivo",
        "Prestação de contas eleitoral",
        "Crime eleitoral",
        "Justiça eleitoral",
        "Recurso eleitoral",
        "Lei da Ficha Limpa",
        "Quociente eleitoral",
        "Diplomação de eleitos",
        "Interdito proibitirio",
        "Nunciaacao de obra nova",
        "Estilo",
        "Posse"
    ],
    [
        "Shopping center",
        "Estacionamento",
        "Franquia",
        "Franqueado"
    ]
]
RANGE_DATES = json.loads(open("range_dates.json").read())

TRIBUNAIS_ESAJ = [
    #"https://esaj.tjac.jus.br/cjsg/consultaCompleta.do",
    #"https://www2.tjal.jus.br/cjsg/consultaCompleta.do",
    #"https://consultasaj.tjam.jus.br/cjsg/consultaCompleta.do",
    #"https://esaj.tjce.jus.br/cjsg/consultaCompleta.do",
    "https://esaj.tjsp.jus.br/cjsg/consultaCompleta.do",
   #"https://esaj.tjms.jus.br/cjsg/consultaCompleta.do"
]




def tjpa(data_inicio, data_fim):

    data_inicio = data_inicio.split("/")
    data_inicio = f"{data_inicio[2]}-{data_inicio[1]}-{data_inicio[0]}"
    data_fim = data_fim.split("/")
    data_fim = f"{data_fim[2]}-{data_fim[1]}-{data_fim[0]}"
    return f"https://jurisprudencia.tjpa.jus.br/?size=n_20_n&filters%5B0%5D%5Bfield%5D=datadocumento&filters%5B0%5D%5Bvalues%5D%5B0%5D%5Bfrom%5D={data_inicio}T03%3A00%3A00.000Z&filters%5B0%5D%5Bvalues%5D%5B0%5D%5Bto%5D={data_fim}T03%3A00%3A00.000Z&filters%5B0%5D%5Btype%5D=any"
    

TRIBUNAIS_SEM_RASPAGEM = {
    "https://tucujuris.tjap.jus.br/tucujuris/pages/consultar-jurisprudencia/consultar-jurisprudencia.html",
    "https://jurisconsult.tjma.jus.br/#/sg-jurisprudence-list"
    "https://jurisprudencia.tjrn.jus.br/"
}


TRIBUNAIS_SISTEMA_PROPRIO = [
    "https://jurisprudencia.tjrr.jus.br/juris/",
    "https://jurisprudencia.tjto.jus.br/",
    "https://www.tjse.jus.br/portal/consultas/jurisprudencia/judicial",
    "https://jurisprudencia.tjba.jus.br/",
    "https://sistemas.tjes.jus.br/consultas_publicas/busca/pje2g",
    "https://www3.tjrj.jus.br/ejuris/ConsultarJurisprudencia.aspx",
    "https://www5.tjmg.jus.br/jurisprudencia/formEspelhoAcordao.do",
    "https://www.jusbrasil.com.br/jurisprudencia/tj-sc/",
    "https://portal.tjpr.jus.br/jurisprudencia/",
    "https://www.tjrs.jus.br/novo/buscas-solr/?aba=jurisprudencia&q=&conteudo_busca=ementa_completa",
    "https://pesquisajuris.tjdft.jus.br/IndexadorAcordaos-web/sistj?visaoId=tjdf.sistj.acordaoeletronico.buscaindexada.apresentacao.VisaoBuscaAcordao",
    "https://projudi.tjgo.jus.br/ConsultaJurisprudencia",
    "https://jurisprudencia.tjmt.jus.br/catalogo",
    
    
    
]



TRIBUNAIS_SERVIDORES_LENTOS = [
"https://www.tjpi.jus.br/e-tjpi/home/jurisprudencia/buscar/ss"
]