from datetime import timedelta
import datetime


CRITERIOS_120 = ['"Seguro residencial" OU "Seguro prestamista" OU "Seguro habitacional" OU "Correção monetária" OU "Juros abusivos"', 
             '"Honorários de sucumbencia" OU "Taxa selic" OU "Seguro de vida" OU "Doença preexistente" OU "Seguro automóvel"', 
             '"Cobertura securitária" OU "Sinistro" OU "Indenização securitária" OU "Cláusula de exclusão" OU "Prêmio de seguro"', 
             '"Reajuste de prêmio" OU "Seguro residencial" OU "Seguro de responsabilidade civil" OU "Boa-fé contratual"', 
             '"Venda casada" OU "Devolução de prêmio" OU "Mora do devedor" OU "Equiparação salarial" OU "Horas extras"', 
             '"Assédio moral" OU "Acidente de trabalho" OU "Vínculo empregatício" OU "Rescisão contratual" OU "Fundo de Garantia"', 
             '"Adicional de insalubridade" OU "Estabilidade provisória" OU "Férias" OU "Décimo terceiro salário"',
             '"Direito sindical" OU "Bancário" OU "Hora adicional" OU "Gerente de agência" OU "Gernte Bancário"', 
             '"Incompetência absoluta" OU "Incompetência relativa" OU "Juros de mora" OU "Locacao" OU "Despejo" OU "Inquilino"',
             '"Valuation" OU "Assédio moral" OU "Balanço específico" OU "Prática abusiva" OU "Vício do produto"', 
             '"Direito de arrependimento" OU "Publicidade enganosa" OU "Proteção contratual" OU "Oferta e demanda"', 
             '"Cobrança indevida" OU "Produto defeituoso" OU "Cláusulas abusivas" OU "Direitos básicos do consumidor"', 
             '"Prazo de garantia" OU "Ação de reparação de danos" OU "Serviço não fornecido" OU "Boa fé" OU "Má fé"', 
             '"Dano material" OU "Contratos" OU "Posse" OU "Usucapião" OU "Direitos reais" OU "Obrigação de fazer"', 
             '"Atos ilícitos" OU "Capacidade civil" OU "Interdito proibitório" OU "Inventário e partilha"', 
             '"Direito Previdenciário" OU "Aposentadoria" OU "Benefício por incapacidade" OU "Pensão por morte"', 
             '"Auxílio-doença" OU "Auxílio-acidente" OU "Salário-maternidade" OU "Desaposentação" OU "Carência"', 
             '"Regime geral de previdência" OU "Benefício assistencial" OU "LOAS" OU "Fator previdenciário"', 
             '"Direito Administrativo" OU "Licitação" OU "Concurso público" OU "Improbidade administrativa" OU "Serviço público"',
             '"Processo administrativo" OU "Servidor público" OU "Regime jurídico único" OU "Controle da administração"', 
             '"Concessão de serviço público" OU "Direito urbanístico" OU "Patrimônio público"',
             '"Autarquia" OU "Direito Constitucional" OU "Direitos fundamentais" OU "Controle de constitucionalidade"',
             '"Ação direta de inconstitucionalidade" OU "Direito à vida" OU "Liberdade de expressão" OU "Direitos sociais"', 
             '"Separação de poderes" OU "Direitos políticos" OU "Estado Democrático de Direito" OU "Poder constituinte"', 
             '"Ação civil pública" OU "Direitos humanos" OU "Direito de Família" OU "Divórcio" OU "Guarda de menores"', 
             '"União estável" OU "Tutela" OU "Adoção" OU "Alimentos" OU "Direito de visitas" OU "Regime de bens" OU "Paternidade"', 
             '"Interdição" OU "Testamento" OU "Herança" OU "Partilha de bens" OU "Direito penal" OU "Habeas corpus"', 
             '"Crime ambiental" OU "Lavagem de dinheiro" OU "Furto" OU "Roubo" OU "Furto simples" OU "Furto qualificado"',
             '"Homicídio" OU "Tráfico de drogas" OU "Lesão corporal" OU "Crimes cibernéticos" OU "Corrupção" OU "Peculato"',
             '"Imputabilidade penal" OU "União estável" OU "Regime de separação parcial" OU "Regime de separação total"', 
             '"Curatela" OU "Correspondente bancario" OU "Usucapião rural" OU "Reforma agrária"',
             '"Conflito de terras" OU "Terra devoluta" OU "Imóvel rural" OU "Cadastro rural" OU "Contrato agrário"',
             '"Parceria agrícola" OU "Direito de preferência" OU "Crédito rural" OU "Produtor rural" OU "Seguro agrícola"',
             '"Cyber Direito" OU "Privacidade na internet" OU "Proteção de dados pessoais" OU "Comércio eletrônico"',
             '"Direito autoral digital" OU "Crimes cibernéticos" OU "Assinatura digital" OU "Certificação digital"',
             '"Redes sociais e direito" OU "Inteligência artificial e direito" OU "E-commerce e responsabilidade"',
             '"Cibersegurança" OU "Blockchain e direito" OU "Provas Digitais" OU "Autenticidade de documentos digitais"',
             '"Forense computacional" OU "Análise de dados digitais" OU "Rastreamento de IP" OU "Recuperação de dados"',
             '"Assinaturas eletrônicas" OU "Interceptação de comunicações digitais" OU "Malware e análise forense"', 
             '"Privacidade e vigilância digital" OU "Big data como prova legal" OU "Redes sociais como evidência"', 
             '"Geolocalização" OU "Inversão do ônus da prova" OU "Prova testemunhal" OU "Prova documental" OU "Prova pericial"',
             '"Presunção de veracidade" OU "Cadeia de custódia" OU "Ônus da prova" OU "Prova ilícita" OU "Interrogatório"', 
             '"Confissão" OU "Acareação" OU "Prova emprestada" OU "Prova técnica" OU "Laudo pericial" OU "Valor probatório"',
             '"Preservação de provas" OU "Prova indiciária" OU "Incidente de falsidade" OU "Prova circunstancial" OU "Vistoria"',
             '"Preclusão probatória" OU "Direito Penal Econômico" OU "Crime contra a ordem econômica" OU "Lavagem de dinheiro"',
             '"Concorrência desleal" OU "Fraude fiscal" OU "Insider trading" OU "Crime contra o sistema financeiro"', 
             '"Pirâmide financeira" OU "Gestão fraudulenta" OU "Evasão de divisas" OU "Fraude em licitações"', 
             '"Corrupção empresarial" OU "Falência fraudulenta" OU "Direito Militar" OU "Crime militar" OU "Justiça militar"',
             '"Hierarquia e disciplina" OU "Deserção" OU "Insubordinação" OU "Motim" OU "Tribunal Militar" OU "Ato de serviço"', 
             '"Processo penal militar" OU "Regulamento disciplinar" OU "Estatuto dos Militares" OU "Reforma militar"', 
             '"Direito Eleitoral" OU "Direitos políticos" OU "Inelegibilidade" OU "Registro de candidatura"', 
             '"Financiamento de campanha" OU "Urna eletrônica" OU "Voto obrigatório" OU "Ação de impugnação de mandato eletivo"', 
             '"Crime eleitoral" OU "Justiça eleitoral" OU "Recurso eleitoral" OU "Lei da Ficha Limpa" OU "Quociente eleitoral"',
             '"Interdito proibitirio" OU "Nunciaacao de obra nova" OU "Estilo" OU "Posse" OU "Shopping center" OU "Estacionamento"',
             '"Franqueado"']
LISTA_CHAVES = [
    
        "Seguro residencial ",
        "Seguro prestamista",
        "Seguro habitacional ",
        "Correção monetária ",
        "Juros abusivos ",
        "Juros",
        "Honorários de sucumbencia",
        "Taxa selic",
        "Seguro de vida",
        "Doença preexistente",
        "Seguro automóvel",
        "Agravamento de risco",
        "Cobertura securitária",
        "Sinistro",
        "Indenização securitária",
        "Cláusula de exclusão",
        "Prêmio de seguro",
        "Franquia",
        "Reajuste de prêmio",
        "Seguro residencial",
        "Seguro de responsabilidade civil",
        "Boa-fé contratual",
        "Perda total",
        "Venda casada",
        "Devolução de prêmio",
        "Mora do devedor",
        "Equiparação salarial",
        "Horas extras",
        "Justa causa",
        "Assédio moral",
        "Acidente de trabalho",
        "Vínculo empregatício",
        "Rescisão contratual",
        "Fundo de Garantia",
        "Adicional de periculosidade",
        "Adicional de insalubridade",
        "Estabilidade provisória",
        "Férias",
        "Décimo terceiro salário",
        "Negociação coletiva",
        "Direito sindical",
        "Bancário ",
        "Hora adicional",
        "Gerente de agência ",
        "Gernte Bancário",
        "Honorários periciais ",
        "Incompetência absoluta ",
        "Incompetência relativa",
        "Juros de mora",
        "Locacao",
        "Despejo",
        "Inquilino ",
        "Mora do devedor ",
        "Valuation",
        "Assédio moral",
        "Balanço específico ",
        "Prática abusiva",
        "Vício do produto",
        "Defeito do produto ",
        "Direito de arrependimento",
        "Publicidade enganosa",
        "Proteção contratual",
        "Oferta e demanda",
        "Serviço defeituoso",
        "Cobrança indevida",
        "Produto defeituoso",
        "Cláusulas abusivas",
        "Direitos básicos do consumidor",
        "Responsabilidade do fornecedor",
        "Prazo de garantia",
        "Ação de reparação de danos",
        "Serviço não fornecido",
        "Boa fé ",
        "Má fé ",
        "Dano moral",
        "Dano material",
        "Contratos",
        "Posse",
        "Usucapião",
        "Direitos reais",
        "Obrigação de fazer",
        "Responsabilidade civil",
        "Atos ilícitos",
        "Capacidade civil",
        "Interdito proibitório",
        "Inventário e partilha",
        "Direito das sucessões",
        "Direito Previdenciário",
        "Aposentadoria",
        "Benefício por incapacidade",
        "Pensão por morte",
        "Contribuição previdenciária",
        "Auxílio-doença",
        "Auxílio-acidente",
        "Salário-maternidade",
        "Desaposentação",
        "Carência",
        "Tempo de contribuição",
        "Regime geral de previdência",
        "Benefício assistencial",
        "LOAS",
        "Fator previdenciário",
        "Revisão de benefício",
        "Direito Administrativo",
        "Licitação",
        "Concurso público",
        "Improbidade administrativa",
        "Serviço público",
        "Ato administrativo",
        "Processo administrativo",
        "Servidor público",
        "Regime jurídico único",
        "Controle da administração",
        "Responsabilidade fiscal",
        "Concessão de serviço público",
        "Direito urbanístico",
        "Patrimônio público",
        "Intervenção do Estado na propriedade",
        "Autarquia",
        "Direito Constitucional",
        "Direitos fundamentais",
        "Controle de constitucionalidade",
        "Mandado de segurança",
        "Ação direta de inconstitucionalidade",
        "Direito à vida",
        "Liberdade de expressão",
        "Direitos sociais",
        "Federalismo",
        "Separação de poderes",
        "Direitos políticos",
        "Estado Democrático de Direito",
        "Poder constituinte",
        "Habeas data",
        "Ação civil pública",
        "Direitos humanos",
        "Direito de Família",
        "Divórcio",
        "Guarda de menores",
        "Pensão alimentícia",
        "União estável",
        "Tutela",
        "Adoção",
        "Alimentos",
        "Direito de visitas",
        "Regime de bens",
        "Paternidade",
        "Investigação de paternidade",
        "Interdição",
        "Testamento",
        "Herança",
        "Partilha de bens",
        "Direito penal",
        "Habeas corpus",
        "Prisão preventiva",
        "Crime ambiental",
        "Lavagem de dinheiro",
        "Furto",
        "Roubo",
        "Furto simples",
        "Furto qualificado ",
        "Estelionato",
        "Homicídio",
        "Tráfico de drogas",
        "Lesão corporal",
        "Crimes cibernéticos",
        "Corrupção",
        "Peculato",
        "Sonegação fiscal",
        "Imputabilidade penal",
        "União estável",
        "Regime de separação parcial",
        "Regime de separação total",
        "Adoção ",
        "Curatela",
        "Correspondente bancario",
        "Usucapião rural",
        "Reforma agrária",
        "Desapropriação para fins de reforma agrária",
        "Conflito de terras",
        "Terra devoluta",
        "Imóvel rural",
        "Cadastro rural",
        "Contrato agrário",
        "Arrendamento rural",
        "Parceria agrícola",
        "Direito de preferência",
        "Crédito rural",
        "Produtor rural",
        "Seguro agrícola",
        "Sustentabilidade no campo",
        "Cyber Direito ",
        "Privacidade na internet",
        "Proteção de dados pessoais",
        "Comércio eletrônico",
        "Contratos digitais",
        "Direito autoral digital",
        "Crimes cibernéticos",
        "Assinatura digital",
        "Certificação digital",
        "Governança digital",
        "Redes sociais e direito",
        "Inteligência artificial e direito",
        "E-commerce e responsabilidade",
        "Fake news e responsabilidade legal",
        "Cibersegurança",
        "Blockchain e direito",
        "Provas Digitais",
        "Autenticidade de documentos digitais",
        "Cadeia de custódia digital",
        "Forense computacional",
        "Análise de dados digitais",
        "Rastreamento de IP",
        "Recuperação de dados",
        "Criptografia e provas digitais",
        "Assinaturas eletrônicas",
        "Interceptação de comunicações digitais",
        "Malware e análise forense",
        "Cloud computing e investigações",
        "Privacidade e vigilância digital",
        "Big data como prova legal",
        "Redes sociais como evidência",
        "Metadados e relevância probatória",
        "Geolocalização ",
        "Inversão do ônus da prova",
        "Prova testemunhal",
        "Prova documental",
        "Prova pericial",
        "Prova digital",
        "Presunção de veracidade",
        "Cadeia de custódia",
        "Ônus da prova",
        "Prova ilícita",
        "Interrogatório",
        "Depoimento pessoal",
        "Confissão",
        "Acareação",
        "Prova emprestada",
        "Prova técnica",
        "Laudo pericial",
        "Valor probatório",
        "Provas ilícitas por derivação",
        "Preservação de provas",
        "Prova indiciária",
        "Incidente de falsidade",
        "Prova circunstancial",
        "Vistoria",
        "Reconhecimento de pessoas e coisas",
        "Preclusão probatória",
        "Direito Penal Econômico",
        "Crime contra a ordem econômica",
        "Lavagem de dinheiro",
        "Sonegação fiscal",
        "Concorrência desleal",
        "Fraude fiscal",
        "Insider trading",
        "Crime contra o sistema financeiro",
        "Mercado de capitais",
        "Pirâmide financeira",
        "Gestão fraudulenta",
        "Evasão de divisas",
        "Fraude em licitações",
        "Crime contra as relações de consumo",
        "Corrupção empresarial",
        "Falência fraudulenta",
        "Direito Militar",
        "Crime militar",
        "Justiça militar",
        "Código Penal Militar",
        "Hierarquia e disciplina",
        "Deserção",
        "Insubordinação",
        "Motim",
        "Tribunal Militar",
        "Ato de serviço",
        "Penalidades militares",
        "Processo penal militar",
        "Regulamento disciplinar",
        "Estatuto dos Militares",
        "Reforma militar",
        "Acidente em serviço",
        "Direito Eleitoral",
        "Direitos políticos",
        "Inelegibilidade",
        "Registro de candidatura",
        "Propaganda eleitoral",
        "Financiamento de campanha",
        "Urna eletrônica",
        "Voto obrigatório",
        "Ação de impugnação de mandato eletivo",
        "Prestação de contas eleitoral",
        "Crime eleitoral",
        "Justiça eleitoral",
        "Recurso eleitoral",
        "Lei da Ficha Limpa",
        "Quociente eleitoral",
        "Diplomação de eleitos",
        "Interdito proibitirio",
        "Nunciaacao de obra nova",
        "Estilo",
        "Posse",
        "Shopping center",
        "Estacionamento",
        "Franquia",
        "Franqueado"
    
]

tribunais_esaj = {
    "AC": "https://esaj.tjac.jus.br/cjsg/consultaCompleta.do",
    "AL": "https://www2.tjal.jus.br/cjsg/consultaCompleta.do",
    "AM": "https://consultasaj.tjam.jus.br/cjsg/consultaCompleta.do",
    "CE": "https://esaj.tjce.jus.br/cjsg/consultaCompleta.do",
    "MS": "https://esaj.tjms.jus.br/cjsg/consultaCompleta.do",
    "SP": "https://esaj.tjsp.jus.br/cjsg/consultaCompleta.do",
    
    
    
}




TRIBUNAIS_SEM_RASPAGEM = {
    "https://tucujuris.tjap.jus.br/tucujuris/pages/consultar-jurisprudencia/consultar-jurisprudencia.html",
    "https://jurisconsult.tjma.jus.br/#/sg-jurisprudence-list"
    "https://jurisprudencia.tjrn.jus.br/"
}


tribunais_sistema_proprio = {
    "RR": "https://jurisprudencia.tjrr.jus.br/juris/",
    "TO": "https://jurisprudencia.tjto.jus.br/",
    "SE": "https://www.tjse.jus.br/portal/consultas/jurisprudencia/judicial",
    "BA": "https://jurisprudencia.tjba.jus.br/",
    "ES": "https://sistemas.tjes.jus.br/consultas_publicas/busca/pje2g",
    
    "RJ": "https://www3.tjrj.jus.br/ejuris/ConsultarJurisprudencia.aspx",
    "MG": "https://www5.tjmg.jus.br/jurisprudencia/formEspelhoAcordao.do",
    "SC": "https://www.jusbrasil.com.br/jurisprudencia/tj-sc/",
    "PR": "https://portal.tjpr.jus.br/jurisprudencia/",
    "RS": "https://www.tjrs.jus.br/novo/buscas-solr/?aba=jurisprudencia&q=&conteudo_busca=ementa_completa",
    "DF": "https://pesquisajuris.tjdft.jus.br/IndexadorAcordaos-web/sistj?visaoId=tjdf.sistj.acordaoeletronico.buscaindexada.apresentacao.VisaoBuscaAcordao",
    "GO": "https://projudi.tjgo.jus.br/ConsultaJurisprudencia",
    "MT": "https://jurisprudencia.tjmt.jus.br/catalogo",
    
    
    
    
}
    
    
    




TRIBUNAIS_SERVIDORES_LENTOS = [
"https://www.tjpi.jus.br/e-tjpi/home/jurisprudencia/buscar/ss"
]





def create_data_range(date_start, date_end, interval):
    """
    Cria uma lista de intervalos de datas entre as datas de início e fim fornecidas.

    Args:
        date_start (str): A data de início no formato "%d/%m/%Y".
        date_end (str): A data de fim no formato "%d/%m/%Y".
        interval (int): O número de dias entre cada intervalo de datas.

    Retorna:
        list: Uma lista de intervalos de datas, onde cada intervalo é representado como uma lista com dois elementos:
              a data de início e a data de fim no formato "%d/%m/%Y".

    Exemplo:
        >>> create_data_range("01/01/2022", "31/01/2022", 7)
        [['01/01/2022', '08/01/2022'], ['08/01/2022', '15/01/2022'], ['15/01/2022', '22/01/2022'], ['22/01/2022', '29/01/2022']]
    """
    date_start = datetime.datetime.strptime(date_start, "%d/%m/%Y")
    date_end = datetime.datetime.strptime(date_end, "%d/%m/%Y")
    date_range = []
    while date_start < date_end:
        date_range.append([date_start.strftime("%d/%m/%Y"), (date_start + timedelta(days=interval)).strftime("%d/%m/%Y")])
        date_start += timedelta(days=interval)
    return date_range
